## Sylvain SCHMITT
## 21/07/2021

ressources: "ressources.genologin.yaml"

# data
refdir: "data/reference"
reference: "Qrob_Chr01_7k"
hz: "Qrob_Chr01_7k_snps.vcf"
libdir: "data/reads/"
base: "trunk"
tumor: ["leaf1", "leaf2"]
