rule bwa_mem:
    input:
        "data/genome.fa",
        "data/samples/A.fastq"
    output:
        "results/mapped_reads/A.sam"
    singularity:
        "oras://registry.forgemia.inra.fr/gafl/singularity/bwa/bwa:latest"
    shell:
        "bwa mem {input} > {output}"
        